# Generated by Django 4.2.9 on 2024-02-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentFurlaxApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
