# Generated by Django 4.1.13 on 2024-02-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentFurlaxApp', '0002_remove_product_category_delete_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
